// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockVerifyService creates a new instance of MockVerifyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifyService {
	mock := &MockVerifyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifyService is an autogenerated mock type for the VerifyService type
type MockVerifyService struct {
	mock.Mock
}

type MockVerifyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifyService) EXPECT() *MockVerifyService_Expecter {
	return &MockVerifyService_Expecter{mock: &_m.Mock}
}

// GetInstalledVersion provides a mock function for the type MockVerifyService
func (_mock *MockVerifyService) GetInstalledVersion(installDir string) (string, error) {
	ret := _mock.Called(installDir)

	if len(ret) == 0 {
		panic("no return value specified for GetInstalledVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(installDir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(installDir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(installDir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifyService_GetInstalledVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstalledVersion'
type MockVerifyService_GetInstalledVersion_Call struct {
	*mock.Call
}

// GetInstalledVersion is a helper method to define mock.On call
//   - installDir string
func (_e *MockVerifyService_Expecter) GetInstalledVersion(installDir interface{}) *MockVerifyService_GetInstalledVersion_Call {
	return &MockVerifyService_GetInstalledVersion_Call{Call: _e.mock.On("GetInstalledVersion", installDir)}
}

func (_c *MockVerifyService_GetInstalledVersion_Call) Run(run func(installDir string)) *MockVerifyService_GetInstalledVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVerifyService_GetInstalledVersion_Call) Return(s string, err error) *MockVerifyService_GetInstalledVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockVerifyService_GetInstalledVersion_Call) RunAndReturn(run func(installDir string) (string, error)) *MockVerifyService_GetInstalledVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Installation provides a mock function for the type MockVerifyService
func (_mock *MockVerifyService) Installation(installDir string, expectedVersion string) error {
	ret := _mock.Called(installDir, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for Installation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(installDir, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVerifyService_Installation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Installation'
type MockVerifyService_Installation_Call struct {
	*mock.Call
}

// Installation is a helper method to define mock.On call
//   - installDir string
//   - expectedVersion string
func (_e *MockVerifyService_Expecter) Installation(installDir interface{}, expectedVersion interface{}) *MockVerifyService_Installation_Call {
	return &MockVerifyService_Installation_Call{Call: _e.mock.On("Installation", installDir, expectedVersion)}
}

func (_c *MockVerifyService_Installation_Call) Run(run func(installDir string, expectedVersion string)) *MockVerifyService_Installation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVerifyService_Installation_Call) Return(err error) *MockVerifyService_Installation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVerifyService_Installation_Call) RunAndReturn(run func(installDir string, expectedVersion string) error) *MockVerifyService_Installation_Call {
	_c.Call.Return(run)
	return _c
}
